_module_src: models.gate
_model_name: GatedAdditiveTreeEnsembleModel
_backbone_name: GatedAdditiveTreesBackbone
_config_name: GatedAdditiveTreeEnsembleConfig

task: classification
head: LinearHead
head_config:
  layers: ""
  activation: ReLU
  dropout: 0.1
  use_batch_norm: false
  initialization: xavier
learning_rate: 1e-3
loss: CrossEntropyLoss
metrics:
  - accuracy
  - f1_score
  - precision
  - recall
  - specificity
  - cohen_kappa
  - auroc
metrics_prob_input:
  - True
  - True
  - True
  - True
  - True
  - True
  - True
metrics_params:
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2}
  - {task: multiclass, num_classes: 2, average: 'macro'}
target_range: null
seed: 42

gflu_stages: 6
gflu_dropout: 0.0
tree_depth: 5
num_trees: 20
binning_activation: sparsemoid
feature_mask_function: sparsemax
tree_dropout: 0.0
chain_trees: True
tree_wise_attention: True
tree_wise_attention_dropout: 0.0
share_head_weights : True
