_module_src: models.tabnet
_model_name: TabNetModel
_backbone_name: TabNetBackbone
_config_name: TabNetModelConfig

task: classification
head: LinearHead
head_config:
  layers: ""
  activation: ReLU
  dropout: 0.1
  use_batch_norm: false
  initialization: xavier
learning_rate: 1e-3
loss: CrossEntropyLoss
metrics:
  - accuracy
  - f1_score
  - precision
  - recall
  - specificity
  - cohen_kappa
  - auroc
metrics_prob_input:
  - True
  - True
  - True
  - True
  - True
  - True
  - True
metrics_params:
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2, average: 'macro'}
  - {task: multiclass, num_classes: 2}
  - {task: multiclass, num_classes: 2, average: 'macro'}
target_range: null
seed: 42

n_d: 8
n_a: 8
n_steps: 3
gamma: 1.3
n_independent: 2
n_shared: 2
virtual_batch_size: 512
mask_type: sparsemax