target:
- Region
continuous_cols:
- IL27
- IL25
- CD40LG
- CCL4
- IL18
- CXCL10
- FLT3L
- CCL2
- VEGFA
- IL1RA
- PDGFA
- PDGFB
- IL13
- IL8
- IL15
- IL5
- TGFA
- TNF
- CCL11
- CXCL9
- IL6
- CX3CL1
- IFNA2
- CCL7
- CCL3
- IL4
- CSF1
- IL12Bp40
- CCL22
- GCSF
- IL1B
- CXCL1
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.25
continuous_feature_transform: yeo-johnson
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true